
from datetime import datetime
from datetime import date

class Customer:
    def __init__(self, customer_name, customer_type, id_number, address, phone_number, registration_date):
        self.customer_id = None  # Generated by the system
        self.customer_name = customer_name
        self.customer_type = customer_type
        self.id_number = id_number
        self.address = address
        self.phone_number = phone_number
        self.registration_date = registration_date
        self.rental_transactions = []
        

class CustomerServiceStaffI:
    global customers
    def __init__(self):
        self.customers = []

    def register_customer(self):

        while True:
            customer_name = input("Key in customer name(type 'done' to finish adding): ")
            if customer_name.lower() == 'done':
                break

            customer_type = input("Input customer type(local or foreigner): ")
            id_number = input("Enter customer id(IC or passport): ")
            address = input("Input customer address: ")
            phone_number = input("Input customer's phone number: ")
            registration_date = date.today()

            customer = Customer(customer_name, customer_type, id_number, address, phone_number, registration_date)
            customer.customer_id = "C" + str(len(self.customers) + 1).zfill(6)
            self.customers.append(customer)
            print("Customer registered successfully. Customer ID:", customer.customer_id)
        customer_service_menu()

        
    def update_customer_details(self):

        while True:
            customer_id = input("Enter customer ID to update details (type 'done' to finish): ")
            if customer_id.lower() == 'done':
                break
            #update this to include reserved a car or not reserved a car.
            found_customer = False
            for customer in self.customers:
                if customer.customer_id == customer_id:
                    phone_number = input("Enter new phone number (leave blank to keep existing): ")
                    address = input("Enter new address (leave blank to keep existing): ")

                    if phone_number:
                        customer.phone_number = phone_number
                    if address:
                        customer.address = address

                    print(f"Details updated for customer ID: {customer_id}")
                    found_customer = True
                    break
            
            if not found_customer:
                print("Customer not found.")
        customer_service_menu()

    def view_registered_customers(self):

        if self.customers:
            print("List of registered customers:")
            for customer in self.customers:
                print(f"Customer ID: {customer.customer_id}")
                print(f"Customer Name: {customer.customer_name}")
                print(f"Customer Type: {customer.customer_type}")
                print(f"ID Number: {customer.id_number}")
                print(f"Address: {customer.address}")
                print(f"Phone Number: {customer.phone_number}")
                print(f"Registration Date: {customer.registration_date}")
                print("----------------------")
        else:
            print("No customers registered yet.")
        customer_service_menu()

    def print_registered_customers(self):
        file = open('customers.txt', 'w')
        if self.customers:
            file.write("List of registered customers: \n")
            for customer in self.customers:
                file.write(f"Customer ID: {customer.customer_id}" + "\n")
                file.write(f"Customer Name: {customer.customer_name}" + "\n")
                file.write(f"Customer Type: {customer.customer_type}" + "\n")
                file.write(f"ID Number: {customer.id_number}" + "\n")
                file.write(f"Address: {customer.address}" + "\n")
                file.write(f"Phone Number: {customer.phone_number}" + "\n")
                file.write(f"Registration Date: {customer.registration_date}" + "\n")
                file.write("----------------------")
        else:
            file.write("No customers registered yet.")
        file.close()
        customer_service_menu()

    def update_own_profile(self):

        global customer_staff_password
        new_password = input("Enter new password: ")
        customer_staff_password = new_password
        users[username]['password'] = new_password
        print("Profile updated successfully.")
        print("Please login again")
        mainfunc()

    def delete_customers_without_rental_transactions(self):
        self.customers = [customer for customer in self.customers if customer.rental_transactions]
        print("Customers without rental transactions deleted successfully.")
        customer_service_menu()

#customer service staff part 2
def car_registration():
    #stops when the variable stop does not equal 1    
    stop = "yes"
    compatible_cars = []
    current_customer = ""
    while stop =="yes":
        customer_found = 0
        customer = str(input("Please enter the customer id: "))
        while customer_found ==0:
            #bloop breaks if customer id is in the array
            for customer2 in staff.customers:
                if customer2.customer_id == customer:
                    customer_found =1
                    current_customer = customer2
                    break
            if customer_found ==0:
                customer = str(input("Please reenter the customer id: "))
        
        seat_cap = int(input("How many seats does the customer want?"))
        for car_plate in cars_list:
            if cars_list[car_plate]["Seating Capacity"] >= seat_cap:
                if cars_list[car_plate]["Rental Availability"] == "available":
                    print("We found a compatible car!")
                    print(cars_list[car_plate])
                    compatible_cars.append(car_plate)
            else:
                print('There is no available car.')
                customer_service_menu()
                
        car_plate = str(input("which car do you want? Type the Car Registration No provided:"))
        
        while car_plate not in compatible_cars:
            car_plate = str(input("please enter a listed car."))

        while True:  
            rental_date= str(input("Please enter the start rental date for this car, in the format day, month, year. For example, 1 February 2024 is 1/2/2024:"))
            try:
            #split separates the input into 3 variables
                day,rental_month,rental_year = map(int,rental_date.split("/"))
                rental_date = datetime(rental_year,rental_month,day)
                break
            except ValueError:
                print("Please enter the correct rental date for this car.")
            

        while True:
            return_date= str(input("Enter the return date for this car, in the format day, month, year. For example, 1 February 2024 is 1/2/2024:"))
            try:
                day,return_month,return_year = map(int,return_date.split("/"))
                return_date = datetime(return_year,return_month,day)
                while ((return_date-rental_date).days+1) <0:
                    return_date= str(input("The return date for this car must be after the rental date, in the format day, month, year:"))
                    day,return_month,return_year = map(int,return_date.split("/"))
                    return_date = datetime(return_year,return_month,day)
                    
                break
            except ValueError:
                print("Please enter the correct return date for this car.")
            
            
        rental_duration = (return_date-rental_date).days +1
        print("The rental duration is",rental_duration,"day(s).")
        
        confirm = str(input("Do you want to confirm this car rental transaction? yes/no:"))
        if confirm == "yes":
            cars_list[car_plate]["Rental Availability"] = "reserved"
        else:
            break
        total_rental = rental_duration * cars_list[car_plate]["Car Renting Rate per day"]


        rental_price = int(input(f"Please pay a total of RM{total_rental}. Input your payment here:"))
        while rental_price < total_rental:
            print("This is less than the rental amount! Please pay the correct total, RM", total_rental)
            rental_price = int(input("Please enter an appropriate amount:"))
        
        car_rental_status = {
        'customer': customer,
        'car_plate': car_plate,
        'rental_date': rental_date,
        'return_date': return_date,
        'total_rental': total_rental,
        'rental_price': rental_price
         }
        
        monthly_revenue = {
        'rental_month' : rental_month,
        'rental_year' : rental_year,
        'rental_price' : cars_list[car_plate]["Car Renting Rate per day"]
        }
        
        #view the rental_transactions at a given date.
        

        #for viewing monthly revenue report based on car rental transactions
        monthly_transaction_details.append(monthly_revenue)

        print(current_customer)
        #to append the car_rental_status dictionary to the customer's transaction history 
        current_customer.rental_transactions.append(car_rental_status)

        #for generating bills
        list_of_transactions.append(customer)
        
        stop = str(input("Do you want to continue adding more rental transactions? yes/no:"))
        
    customer_service_menu()

def generate_bill():
    if not list_of_transactions:
        print("No transactions available.")
        mainfunc()

    
    for x in list_of_transactions:
        print(x)
    bill = str(input("which customer do you want to generate a bill for? "))
    while bill not in list_of_transactions:
        bill = str(input("input a valid customer:"))

    for customer in staff.customers:
        if customer.customer_id == bill:
            current_customer = customer
            # this will assign the current customer's rental transactions to y, so i can print the details.        
            for y in current_customer.rental_transactions:
                print('current customer:',y['customer'])
                print(f"Car Plate: {y['car_plate']}")
                print(f"Rental Date: {y['rental_date']}")
                print(f"Return Date: {y['return_date']}")
                print(f"Total Rental: RM {y['total_rental']}")
                print(f"Amount Paid: RM {y['rental_price']}")
                break
            print("----------------------")
    customer_service_menu()

def date_transactions():
    if not list_of_transactions:
        print("No transactions available.")
        mainfunc()

    while True:  
            desired_date= str(input("Please enter the date you want to view the transactions for. For example, 1 February 2024 is 1/2/2024: "))
            try:
            #split separates the input into 3 variables
                day,rental_month,rental_year = map(int,desired_date.split("/"))
                desired_date = datetime(rental_year,rental_month,day)
                break
            except ValueError:
                print("Please enter the correct rental date for this car.")
    
    for customer in staff.customers:
        #now_date becomes an array of dictionaries of the customers rental transactions
        for now_date in customer.rental_transactions:
            if now_date['rental_date'] == desired_date:
                current_customer = customer
                # this will assign the current customer's rental transactions to y, so i can print the details.  
                for y in current_customer.rental_transactions:
                    print(y['car_plate'])
                    print(f"Car Plate: {y['car_plate']}")
                    print(f"Rental Date: {y['rental_date']}")
                    print(f"Return Date: {y['return_date']}")
                    print(f"Total Rental: RM {y['total_rental']}")
                    print(f"Amount Paid: RM {y['rental_price']}")
        
        print("----------------------")
    customer_service_menu()

#Manager Part 1
def reg_new_staff():
    print ("====== Register New Staff ======")
    staff_id = str(input("Staff Registration Number: "))
    while staff_id in users:
        print("Staff ID already exists")
        staff_id = str(input("Staff Registration Number: "))
    else:
        staff_name = str(input("Staff Name: "))
        staff_role = str(input("Staff Role (manager, car service staff, customer service staff): "))
        while staff_role not in ['manager','car service staff','customer service staff']:
            staff_role = str(input("Staff Role (manager, car service staff, customer service staff): "))
        staff_password = str(input("Enter the new staff password:"))
        reg_date = str(input("Date of staff registration in the format DD/MM/YYYY: "))
        while validate_date(reg_date)== False:
            print("Invalid date.")
            reg_date = str(input("Date of staff registration in the format DD/MM/YYYY: "))
        staff_active = "active"
    new_staff = {
        staff_id : {
        "name" : staff_name,
        "role" : staff_role,
        "password" : staff_password,
        "date of registration" : reg_date,
        "active status" : staff_active
        }
    }
    users.update(new_staff)
    manager_menu()

def update_staff_det():
    print("====== Update Staff Details ======")
    while True:
        staff_id = input("Enter staff ID to update details (type 'done' to finish): ")
        if staff_id.lower() == 'done':
            break
            #update this to include reserved a car or not reserved a car.
        found_staff = False
        for current_staff in users:
            if staff_id == current_staff:
                
                new_staff_id = str(input("New Staff id, leave blank if unchanged:"))
                staff_name = str(input("Staff Name, leave blank if unchanged: "))
                staff_role = str(input("Staff Role (manager, car service staff, customer service staff): "))
                while staff_role not in ['manager','car service staff','customer service staff']:
                    staff_role = str(input("Staff Role (manager, car service staff, customer service staff): "))
                staff_password = str(input("Enter the new staff password:"))

                update_date = str(input("Do you want to register a new registration date? yes/no"))
                if update_date == 'yes':
                    reg_date = str(input("Date of staff registration in the format DD/MM/YYYY: "))
                    while validate_date(reg_date)== False:
                        print("Invalid date.")
                        reg_date = str(input("Date of staff registration in the format DD/MM/YYYY: "))
                    users[staff_id]['staff registration'] = reg_date
                staff_active = str(input("Is staff resigned or active?"))
                while staff_active not in ['resigned','active']:
                    staff_active = str(input("Is staff resigned or active?"))
                #'tom': {'name':'Thomas','password': 'password123', 'role': 'car service staff',"active status":"active"}
                #checks if the variable has an input in it
                 
                    
                if staff_name:
                    users[staff_id]['name'] = staff_name
                if staff_role:
                    users[staff_id]['role'] = staff_role
                if staff_password:
                    users[staff_id]['password'] = staff_password
                if new_staff_id:
                    users[staff_id] = new_staff_id
                
                
                print(f"Details updated for staff ID: {staff_id}")
                found_staff = True
                break
            
        if found_staff == False:
            print("Staff not found.")
        
    manager_menu()

#outputs staff list
def view_staff_list():
    for x, obj in users.items():
        print(x)
        for y in obj.keys():
            print(y + ":", obj[y])
    manager_menu()

def delete_resigned():
    #creates an array of users to delete to prevent a runtime error
    users_to_delete = []
    for current_user in users:
        if users[current_user]["active status"] == 'resigned':
            users_to_delete.append(current_user)
    for i in users_to_delete:
        users.pop(i)        

    print("resigned staff has been removed.")
    manager_menu()


#prints to file
def print_staff_list():
    file = open("staff_list.txt","w")
    for x, obj in users.items():
        file.write(x + "\n")
        for y,k in obj.items():
            file.write(f"{y}: {k}\n")
    file.close()
    manager_menu()

def car_renting_rate():
    while True:
        try:
            car_seats = int(input("Enter the seat that you want to change the renting rate for. 4, 7 or 9 seater: "))
            while car_seats not in (4,7,9):
                car_seats = int(input("Enter the seat that you want to change the renting rate for. 4, 7 or 9 seater: "))
            break
        except ValueError:
            print("You must enter an integer number")

    while True:
        try:
            car_renting_rate = int(input("Enter the car renting rate that you want to change the renting rate to:"))
            break
        except ValueError:
            print("You must enter an integer number")

    for x in cars_list:
            if cars_list[x]["Seating Capacity"] == car_seats:
                cars_list[x]["Car Renting Rate per day"] = car_renting_rate
            else:
                print('There is no available car with the seat number.')
    manager_menu()

def view_monthly_revenue_report():
    total = 0
    while True:
        try:
            year =  int(input("Please enter the year of the month you want to generate:"))
            # if the length of the year is more than 4 something is wrong
            while year<1000 or year>9999:
                year =  int(input("Please reenter the year you want to generate:"))
            break
        except ValueError:
            print("invalid year")

    while True:
        try:
            month =  int(input("Please enter the month you want to generate:"))
            # if the length of the year is more than 4 something is wrong
            while month<0 or month >12:
                month =  int(input("Please reenter the month you want to generate:"))
            break
        except ValueError:
            print("invalid month")
    
    for current_x in monthly_transaction_details:
        if month == current_x["rental_month"] and year == current_x["rental_year"]:
            total = total + current_x['rental_price']
    
    print("your total rental price for this month is, RM",total)


#Part 4 Car Service Staff      
def reg_newcar():
    print ("====== Register New Car ======")
    reg_num = str(input("Car Registration Number: "))
    while reg_num in cars_list:
        print("Car Registration No already exists")
        reg_num = str(input("Car Registration Number: "))
    else:
        manu = str(input("Car Manufacturer: "))
        model = str(input("Car Model: "))
        manu_year = str(input("Year of Manufacture: "))
        while len(manu_year) != 4:
            manu_year = str(input("Year of Manufacture: "))
        seat_cap = int(input("Seating Capacity: "))
        print("Last Service Date")
        service_date = input_date()
        inspol_num = str(input("Insurance Policy Number: "))
        print("Insurance Expiry Date")
        ins_exp = input_date()
        print("Road Tax Expiry Date")
        roadtax_exp = input_date()
    new_car = {
        reg_num : {
        "Car Registration No" : reg_num,
        "Car Manufacturer" : manu,
        "Car Model" : model,
        "Year of Manufacture" : manu_year,
        "Seating Capacity" : seat_cap,
        "Last Service Date" : service_date,
        "Insurance Policy Number" : inspol_num,
        "Insurance Expiry Date" : ins_exp,
        "Road Tax Expiry Date" : roadtax_exp,
        "Car Renting Rate per day" : "",
        "Rental Availability" : "available"
        }
    }
    cars_list.update(new_car)
    car_staff_menu()
    
def update_cardet():
    print("====== Update Car Details ======")
    reg_num = str(input("Car Registration Number: "))
    while reg_num not in cars_list:
        print("car registration number not in system")
        reg_num = str(input("Car Registration Number: "))
    for x, obj in cars_list.items():
        if x == reg_num:
            print(x)
            for y in obj:
                print(y + ":", obj[y])
    inspol_num = str(input("\nInsurance Policy Number: "))
    print("Insurance Expiry Date")
    ins_exp = input_date()
    print("Road Tax Expiry Date")
    roadtax_exp = input_date()
    rentrate = float(input("Car Renting Rate per day: "))
    rental_availability = str(input("Rental Availability(available/ reserved/ rented/ under service/ disposed): "))
    while rental_availability not in ("available", "reserved", "rented", "under service", "disposed"):
        print ("Please only enter options given")
        rental_availability = str(input("Rental Availability(available/ reserved/ rented/ under service/ disposed): "))
    cars_list[reg_num]["Insurance Policy Number"] = inspol_num
    cars_list[reg_num]["Insurance Expiry Date"] = ins_exp
    cars_list[reg_num]["Road Tax Expiry Date"] = roadtax_exp
    cars_list[reg_num]["Car Renting Rate per day"] = rentrate
    cars_list[reg_num]["Rental Availability"] = rental_availability

    if rental_availability == "disposed":
        cars_list.pop(reg_num)
    if rental_availability == "rented":
        print("Returning Date")
        return_date = input_date()
        cars_list[reg_num]["Returning Date"] = return_date
    car_staff_menu()


def view_carlist():
    for x, obj in cars_list.items():
        print(x)
        for y in obj:
            print(y + ":", obj[y])
    car_staff_menu()

def print_carlist():
    file = open("cars_list.txt","w")
    for x, obj in cars_list.items():
        file.write(x + "\n")
        for y,k in obj.items():
            file.write(f"{y}: {k}\n")
    file.close()
    car_staff_menu()
    
def validate_date(date_string):
    try:
        datetime.strptime(date_string, '%d/%m/%Y')
        return True
    except ValueError:
        return False

def input_date():
    while True:
        date = input("Please enter a date in the format DD/MM/YYYY: ")
        if validate_date(date):
            return date
        else:
            print("Invalid date format. Please try again.")

def update_profile():
    new_password = str(input("Please enter your new password"))
    users[username]['password'] = new_password
    print("Profile updated successfully.")
    print("Please log in again")
    mainfunc()





list_of_transactions = []
monthly_transaction_details = []
rental_transactions = {}
staff = CustomerServiceStaffI()
current_customer = "-"
users = {
    'alex': {'name':'Alex Shake','password': '12345', 'role': 'manager',"active status":"active","staff registration": ""},
    'bob': {'name':'Bob Builder','password': '123', 'role': 'customer service staff',"active status":"active",'staff registration':""},
    'tom': {'name':'Thomas','password': 'password123', 'role': 'car service staff',"active status":"resigned","staff registration":""}
}

cars_list = {'WUV1234': {'Car Registration No': 'WUV1234', 
                     'Car Manufacturer': 'sdfghjk', 
                     'Car Model': 'vbnm', 
                     'Year of Manufacture': '2009', 
                     'Seating Capacity': 9, 
                     'Last Service Date': '09/09/2009', 
                     'Insurance Policy Number': '456', 
                     'Insurance Expiry Date': '08/08/2008',
                     'Road Tax Expiry Date': '07/07/2007',
                     'Car Renting Rate per day': 400,
                     'Rental Availability':'available'},
            'VDA5241': {'Car Registration No': 'VDA5241', 
                     'Car Manufacturer': 'sdfghjk', 
                     'Car Model': 'vbnm', 
                     'Year of Manufacture': '2009', 
                     'Seating Capacity': 9, 
                     'Last Service Date': '09/09/2009', 
                     'Insurance Policy Number': '456', 
                     'Insurance Expiry Date': '08/08/2008',
                     'Road Tax Expiry Date': '07/07/2007',
                     'Car Renting Rate per day': 400,
                     'Rental Availability':'available'}}




def manager_menu():
    print ("\nMANAGER MENU \n1. Register staff \n2. Update staff \n3. View list of staff \n4. Update profile \n5. Delete resigned staff \n6. Update car renting rate \n7. Output staff list to text file \n8. View monthly revenue report \n9. Logout")
    choice = str(input("\nSelect next action (1/2/3/4/5/6/7/8): "))
    while choice not in ('1','2','3','4','5','6','7','8'):
        str(input("Select either 1/2/3/4/5/6/7/8: "))
    if choice == '1':
        reg_new_staff()
    if choice == '2':
        update_staff_det()
    if choice == '3':
        view_staff_list()
    if choice == '4':
        update_profile()
    if choice == '5':
        delete_resigned()
    if choice == '6':
        car_renting_rate()
    if choice == '7':
        print_staff_list()
    if choice == '8':
        view_monthly_revenue_report()
    if choice == '9':
        mainfunc()


def customer_service_menu():
    global staff
    
    print ("""\nCUSTOMER SERVICE STAFF MENU
           1. Register customers
           2. Update customer details
           3. View list of customers
           4. Update profile
           5. Delete customers with no rental transactions
           6. Register a new rental transaction
           7. View rental transactions at a given date
           8. Generate a bill
           9. Write customers to a txt file
           10. Logout""")
    choice = str(input("\nSelect next action (1/2/3/4/5/6/7/8/9): "))
    while choice not in ('1','2','3','4','5','6','7','8','9'):
        choice = str(input("Select either 1/2/3/4/5/6/7/8/9: "))
    if choice == '1':
        staff.register_customer()
    if choice == '2':
        while True:
            staff.update_customer_details()
            continue_update = input("Do you want to update more customers? (yes/no): ")
            if continue_update.lower() != 'yes':
                break
    if choice == '3':
        staff.view_registered_customers()
    if choice == '4':
        staff.update_own_profile()
    if choice == '5':
        staff.delete_customers_without_rental_transactions()
    if choice == '6':
        car_registration()
    if choice == '7':
        date_transactions()  
    if choice == '8':
        generate_bill()
    if choice == '9':
        staff.print_registered_customers()
    if choice == '10':
        mainfunc()  

def car_staff_menu():
    print ("\nCAR SERVICE STAFF MENU \n1. Register new car \n2. Update car details \n3. View list of cars \n4. Update profile \n5. Output cars list to txt file \n6. Logout")
    choice = str(input("\nSelect next action (1/2/3/4/5/6): "))
    while choice not in ("1","2","3","4","5","6"):
        choice = str(input("Select either 1/2/3/4/5/6: "))
    if choice == '1':
        reg_newcar()
    if choice == '2':
        update_cardet()
    if choice == '3':
        view_carlist()
    if choice == '4':
        update_profile()
    if choice == '5':
        print_carlist()
    if choice == '6':
        mainfunc()

def login(username,password):
    global role
    if username in users:
        #if password is correct, it returns True from the function. else, the function returns false.
        if password == users[username]['password']:
            role = users[username]['role']
            return True
        else:
            return False
        
def mainfunc():
    #allows username to be accessed in the first function
    global staff
    global username
    
    login_attempts = 0
    while login_attempts <3:
        username = str(input("Please enter your username:"))
        password = str(input("Please enter your password:"))
        # if the output of the login function is True, the loop breaks.
        if login(username,password):
            print("you have been authenticated. Your role is,",role)
            break
        else:
            print("please reenter your credentials.")
            login_attempts = login_attempts +1
            if login_attempts == 3:
                print("You have exceeded the total number of logins. Try again later.")
    
    if role == "manager":
        manager_menu()

    if role == "customer service staff":
        customer_service_menu()

    if role == "car service staff":
        car_staff_menu()
    
mainfunc()
